name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Gradle
        run: ./gradlew build --no-daemon

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Lint (Gradle check)
        run: ./gradlew check --no-daemon

  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run unit tests
        run: ./gradlew test --no-daemon

  mutation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Mutation testing (placeholder)
        run: echo "No mutation testing tool configured. Add pitest or similar to enable this step."

  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: docker build -t app-under-test .
      - name: Cleanup previous container
        run: docker rm -f app-smoke || true
      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 --name app-smoke app-under-test
          sleep 15
      - name: Smoke test health endpoint
        run: |
          curl -f http://localhost:8080/actuator/health
      - name: Show logs on failure
        if: failure()
        run: docker logs app-smoke || true
      - name: Cleanup
        run: docker rm -f app-smoke || true
